### sanity check of the scores

In [2]:
import pandas as pd
df = pd.read_csv(
    filepath_or_buffer = "/Users/santiagocardenas/Documents/MDSI/202502/internship/internship_project/data/processed/scores.csv",
    index_col = ["candidate_id", "group_id"]
)
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26 entries, ('af62b86c3a326086', np.int64(2)) to ('c5f45dfe145427e1', np.int64(0))
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Data Analytics             26 non-null     int64
 1   Business Transformation    26 non-null     int64
 2   Consulting                 26 non-null     int64
 3   Data Management            26 non-null     int64
 4   Information Technology     26 non-null     int64
 5   Data Modeling              26 non-null     int64
 6   ETL Processes              26 non-null     int64
 7   Data Governance            26 non-null     int64
 8   Data Visualization         26 non-null     int64
 9   Analytics Integration      26 non-null     int64
 10  Problem Solving            26 non-null     int64
 11  Client Engagement          26 non-null     int64
 12  Team Collaboration         26 non-null     int64
 13  Effective Communication    26 non-null     int64
 14  Adaptability               26 non-null     int64
 15  Passion for Innovation     26 non-null     int64
 16  Synergy and Collaboration  26 non-null     int64
 17  Continuous Improvement     26 non-null     int64
 18  Proactive Learning         26 non-null     float64
 19  Commitment to Excellence   26 non-null     float64
 20  overall                    26 non-null     float64
dtypes: float64(3), int64(18)
memory usage: 5.9+ KB

In [8]:
df.head()

,,Data Analytics,Business Transformation,Consulting,Data Management,Information Technology,Data Modeling,ETL Processes,Data Governance,Data Visualization,Analytics Integration,...,Client Engagement,Team Collaboration,Effective Communication,Adaptability,Passion for Innovation,Synergy and Collaboration,Continuous Improvement,Proactive Learning,Commitment to Excellence,overall
candidate_id,group_id,,,,,,,,,,,,,,,,,,,,,
af62b86c3a326086,2,85,80,70,90,75,80,70,65,85,82,...,90,65,80,88,75,85,80,90.0,0.0,76.02
b5142b9b9676a4f9,0,85,80,75,90,85,90,80,70,90,85,...,80,90,80,90,85,90,90,95.0,0.0,80.80
de4e24b044e42f42,3,70,60,65,75,50,80,55,60,70,80,...,85,70,70,60,65,80,85,75.0,0.0,66.90
8821085d3ae9e0ce,2,90,70,80,85,75,80,80,85,70,90,...,80,85,80,90,75,80,85,90.0,0.0,78.00
90e485656ce9236d,2,85,80,75,90,95,90,85,80,90,85,...,95,95,80,90,80,85,90,95.0,90.0,87.15

In [3]:
weights = [25, 30, 25, 20]
domains = ["Data Analytics", "Business Transformation", "Consulting", "Data Management", "Information Technology"]
tech_skills = ["Data Modeling", "ETL Processes", "Data Governance", "Data Visualization", "Analytics Integration"]
soft_skills = ["Problem Solving", "Client Engagement", "Team Collaboration", "Effective Communication", "Adaptability"]
culture = ["Passion for Innovation", "Synergy and Collaboration", "Continuous Improvement", "Proactive Learning", "Commitment to Excellence"]
all_criteria = domains + tech_skills + soft_skills + culture
print(f"the lenght of weights is: {len(weights)}")
print(f"the lenght of weights is: {len(all_criteria)}")

the lenght of weights is: 4
the lenght of weights is: 20

In [4]:
print(f"the total number of columns: {len(df.columns)}")

the total number of columns: 21

In [7]:
missing_column = set(df.columns.to_list()) - set(all_criteria)
print(missing_column)

{'overall'}

In [10]:
df.sort_values(by = 'overall', ascending = False).head(3)

,,Data Analytics,Business Transformation,Consulting,Data Management,Information Technology,Data Modeling,ETL Processes,Data Governance,Data Visualization,Analytics Integration,...,Client Engagement,Team Collaboration,Effective Communication,Adaptability,Passion for Innovation,Synergy and Collaboration,Continuous Improvement,Proactive Learning,Commitment to Excellence,overall
candidate_id,group_id,,,,,,,,,,,,,,,,,,,,,
90e485656ce9236d,2,85,80,75,90,95,90,85,80,90,85,...,95,95,80,90,80,85,90,95.0,90.0,87.15
6700f96c37c87933,2,90,85,80,95,90,95,90,85,93,88,...,95,91,90,95,85,93,90,95.0,0.0,86.73
8ed9c5e84fb32c65,0,90,85,80,95,90,88,92,95,87,85,...,88,90,92,85,90,95,90,88.0,0.0,85.09

In [15]:
col_weght_map = {
    c : weights[index//5]/500 for index, c in enumerate(df.columns) if c in all_criteria
}
col_weght_map

{'Data Analytics': 0.05,
 'Business Transformation': 0.05,
 'Consulting': 0.05,
 'Data Management': 0.05,
 'Information Technology': 0.05,
 'Data Modeling': 0.06,
 'ETL Processes': 0.06,
 'Data Governance': 0.06,
 'Data Visualization': 0.06,
 'Analytics Integration': 0.06,
 'Problem Solving': 0.05,
 'Client Engagement': 0.05,
 'Team Collaboration': 0.05,
 'Effective Communication': 0.05,
 'Adaptability': 0.05,
 'Passion for Innovation': 0.04,
 'Synergy and Collaboration': 0.04,
 'Continuous Improvement': 0.04,
 'Proactive Learning': 0.04,
 'Commitment to Excellence': 0.04}

In [16]:
overall_v2 = sum(df[c] * w for c, w in col_weght_map.items())
overall_v2

candidate_id      group_id
af62b86c3a326086  2           76.02
b5142b9b9676a4f9  0           80.80
de4e24b044e42f42  3           66.90
8821085d3ae9e0ce  2           78.00
90e485656ce9236d  2           87.15
77aacb560b1dd217  1           82.60
c69f2087775fc760  2           81.78
f476ce0793a219b1  1           73.20
e5f8984dfa4cae3b  1           84.25
6700f96c37c87933  2           86.73
8ed9c5e84fb32c65  0           85.09
493d0d19e0150412  3           72.90
dd417e3f63181d20  3           81.25
4a9374ec3b2ca204  3           79.95
a8ca1108dd06b907  0           83.29
2b4c705e8b2a0770  1           79.20
ccfed7e7060c9916  1           62.40
c9cddf5fb828eab6  0           82.10
fae54469e0d024e8  3           77.70
6d743d56d9692fd0  1           77.60
adbef5e743bf5c48  2           69.15
0176a86af53206ae  0           83.15
f2ca85739fda42e4  1           80.40
934d1fdb8a6d1063  3           77.90
1f04921d492de215  0           80.40
c5f45dfe145427e1  0           84.69
dtype: float64

In [18]:
all(overall_v2 == df['overall'])

True

### structured output for relevant job experience

In [ ]:
from pydantic import BaseModel, Field
from typing import List, Optional
from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv
from langchain_groq import ChatGroq

load_dotenv()
llm = ChatGroq(
    model = "llama-3.1-8b-instant"
)

class JobExperience(BaseModel):
    """Details about a single job experience."""
    job_title: str = Field(..., description="The candidate's job title.")
    company_name: str = Field(..., description="The name of the company.")
    years_of_experience: str = Field(..., description="The duration of employment (e.g., '2020 - 2023' or '2 years').")
    responsibilities: List[str] = Field(..., description="A list of key responsibilities and accomplishments.")

class CandidateExperience(BaseModel):
    """The structured extraction of a candidate's professional experience."""
    experience: List[JobExperience] = Field(..., description="A list of all professional experiences listed on the resume.")

extraction_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        (
            "You are an expert recruiter. Your task is to extract all professional experience from a candidate's resume "
            "into a structured JSON format. Provide all job titles, company names, years of experience, and "
            "a concise list of responsibilities for each role."
        ),
    ),
    (
        "human",
        (
            "Please extract the professional experience from the following resume:\n\n{resume}"
        ),
    ),
])

llm_constrained = llm.with_structured_output(schema = CandidateExperience)
extraction_chain = extraction_prompt | llm_constrained

In [20]:
from functions import text_extraction
sample_resume = text_extraction(
    file_path = "/Users/santiagocardenas/Documents/MDSI/202502/internship/internship_project/data/raw/cv/90e485656ce9236d-Qudrat Ali.docx"
)
msg = extraction_chain.invoke({
    "resume" : sample_resume
})
msg

CandidateExperience(experience=[JobExperience(job_title='Data Analyst', company_name='Next Wave MSP, Australia', years_of_experience='Jan 2024 â€“ Present', responsibilities=['Designed and monitored secure, end-to-end data pipelines, transforming raw data into analytics-ready formats using tools like dbt, Databricks, and SQL-based transformations.', 'Built interactive dashboards in Power BI and Tableau to visualize performance metrics, sentiment analysis, and call outcomesâ€”enabling real-time monitoring of customer experience KPIs.', 'Collaborated with data engineers and scientists to tune and integrate machine learning models into voice analytics workflows, enhancing system adaptability and business relevance.', 'Conducted deep-dive analyses using SQL, Python, R, and cloud platforms (BigQuery, Snowflake, Azure) to extract meaningful trends and drive strategic, data-informed decisions.', 'Applied data governance and documentation practices to improve data quality, pipeline transparency, and team-wide accessibility to structured and unstructured datasets.', 'Worked with cross-functional stakeholders to understand business challenges and deliver tailored data science and analytics solutions that support innovation and long-term growth.', 'Partnered with technical and non-technical teams to ensure secure data migration and integration, identifying potential risks and issues and supporting pre-deployment testing phases.', 'Contributed to NLP model optimization for transcription and sentiment tagging, aligning data science models with contact center monitoring goals.', 'Supported continuous improvement by evaluating emerging tools, optimizing workflows, and applying best practices across analytics and data science functions.', 'Known for excellent communication skills and ability to collaborate in agile, cross-functional teams to meet tight deadlines and evolving client requirements.']), JobExperience(job_title='Customer Service Representative', company_name='United Fuel Pump, VIC, Australia', years_of_experience='Aug 2023 â€“ Jan 2024', responsibilities=['Helped customers with fuel transactions, always making sure to provide friendly and fast service.', 'Managed the cash register, handling payments with cash, card, or loyalty points.', 'Restocked shelves and kept track of inventory to make sure products were available when customers needed them.', 'Took the time to listen to customer questions and resolve any concerns in a professional and helpful way.', 'Followed safety guidelines for handling fuel and made sure the work environment stayed safe and secure.', 'Assisted with everyday station tasks, like opening, closing, and completing end-of-day reports.']), JobExperience(job_title='Intern', company_name='Pantech, India', years_of_experience='Jan 2023 â€“ Jun 2023', responsibilities=['Contributed to gathering, cleaning, and preparing large datasets for analysis, ensuring the data was both accurate and reliable.', 'Performed exploratory data analysis (EDA) to uncover trends and patterns.', 'Developed interactive dashboards and visualizations using Tableau and Power BI to present key insights to stakeholders.', 'Wrote SQL queries to retrieve data from relational databases for reporting and analysis purposes.', 'Assisted in the development of predictive models by selecting features and testing various algorithms.', 'Monitored the integrity of data throughout the ETL process to ensure smooth and accurate data integration.'])])

In [21]:
total_job_experience = len(msg.experience)

In [22]:
total_job_experience

3

In [24]:
msg.model_dump()

{'experience': [{'job_title': 'Data Analyst',
   'company_name': 'Next Wave MSP, Australia',
   'years_of_experience': 'Jan 2024 â€“ Present',
   'responsibilities': ['Designed and monitored secure, end-to-end data pipelines, transforming raw data into analytics-ready formats using tools like dbt, Databricks, and SQL-based transformations.',
    'Built interactive dashboards in Power BI and Tableau to visualize performance metrics, sentiment analysis, and call outcomesâ€”enabling real-time monitoring of customer experience KPIs.',
    'Collaborated with data engineers and scientists to tune and integrate machine learning models into voice analytics workflows, enhancing system adaptability and business relevance.',
    'Conducted deep-dive analyses using SQL, Python, R, and cloud platforms (BigQuery, Snowflake, Azure) to extract meaningful trends and drive strategic, data-informed decisions.',
    'Applied data governance and documentation practices to improve data quality, pipeline transparency, and team-wide accessibility to structured and unstructured datasets.',
    'Worked with cross-functional stakeholders to understand business challenges and deliver tailored data science and analytics solutions that support innovation and long-term growth.',
    'Partnered with technical and non-technical teams to ensure secure data migration and integration, identifying potential risks and issues and supporting pre-deployment testing phases.',
    'Contributed to NLP model optimization for transcription and sentiment tagging, aligning data science models with contact center monitoring goals.',
    'Supported continuous improvement by evaluating emerging tools, optimizing workflows, and applying best practices across analytics and data science functions.',
    'Known for excellent communication skills and ability to collaborate in agile, cross-functional teams to meet tight deadlines and evolving client requirements.']},
  {'job_title': 'Customer Service Representative',
   'company_name': 'United Fuel Pump, VIC, Australia',
   'years_of_experience': 'Aug 2023 â€“ Jan 2024',
   'responsibilities': ['Helped customers with fuel transactions, always making sure to provide friendly and fast service.',
    'Managed the cash register, handling payments with cash, card, or loyalty points.',
    'Restocked shelves and kept track of inventory to make sure products were available when customers needed them.',
    'Took the time to listen to customer questions and resolve any concerns in a professional and helpful way.',
    'Followed safety guidelines for handling fuel and made sure the work environment stayed safe and secure.',
    'Assisted with everyday station tasks, like opening, closing, and completing end-of-day reports.']},
  {'job_title': 'Intern',
   'company_name': 'Pantech, India',
   'years_of_experience': 'Jan 2023 â€“ Jun 2023',
   'responsibilities': ['Contributed to gathering, cleaning, and preparing large datasets for analysis, ensuring the data was both accurate and reliable.',
    'Performed exploratory data analysis (EDA) to uncover trends and patterns.',
    'Developed interactive dashboards and visualizations using Tableau and Power BI to present key insights to stakeholders.',
    'Wrote SQL queries to retrieve data from relational databases for reporting and analysis purposes.',
    'Assisted in the development of predictive models by selecting features and testing various algorithms.',
    'Monitored the integrity of data throughout the ETL process to ensure smooth and accurate data integration.']}]}